### ISSUE TITLE
There are some warnings keep showing

### ISSUE THREAD

**Issue by basicallynewbie** [Just5KY/honeypots#3]
I just changed some external ports and used the Docker compose,and this warnings keep showing,is it normal?
```
/usr/local/lib/python3.10/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.10) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
```

**Comment by just5ky** [comment]
Is this happening on all protocols or just one?

Might be because of python 3.10

**Comment by basicallynewbie** [comment]
I couldn't tell.The log only shows in portainer.And all logs about one thousand in /honeypots/logs are empty.
[honeypots_logs.txt](https://github.com/Just5KY/honeypots/files/9181586/honeypots_logs.txt)

**Comment by just5ky** [comment]
I still have to work on deployment using docker-compose.

When you do “setup all”, all the protocol honeypots are started, that's why there are various empty files in logs.

Also, I checked my deployments and saw it was HTTPS, HTTP, HTTP-Proxy
![image](https://user-images.githubusercontent.com/71321862/180800747-a7e81d89-78ab-4e8a-90a5-43fd10797567.png)
![image](https://user-images.githubusercontent.com/71321862/180800986-5ef49afd-ac94-4239-b98e-3fa9ca9086f2.png)
![image](https://user-images.githubusercontent.com/71321862/180801269-051bb140-8af5-4b1a-b461-ce704526ffe9.png)

The honeypots are working fine, even with the warning.

**Comment by basicallynewbie** [comment]
OK,then.I will ignore those warnings.
